bunky/urls.py
from django.urls import path

from . import views

app_name = 'bunky'
urlpatterns = [
	path('', views.MainView.as_view(), name='main'),
	path('find/', views.find, name='find'),
	path('home/<int:user_id>/', views.home, name='home'),
	path('bunk/<int:user_id>/', views.bunk, name='bunk'),
	path('bunked/<int:pk>/', views.BunkedView.as_view(), name='bunked'),
]

jitterbunk/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('bunky.urls')),
    path('admin/', admin.site.urls),
]

bunky/models.py
import datetime

from django.db import models
from django.utils import timezone

# Models

# An account on Jitterbunk
class User(models.Model):

	username = models.CharField(max_length=50) # Name of user
	photo = models.CharField(max_length=2000) # TBD

	def __str__(self):
		return self.username

# A 'Bunk'
class Bunk(models.Model):

	from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user') # FK of sending user
	to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user') # FK of receiving user
	time = models.DateTimeField('time of bunk') # Time that bunk was bunk'd

	def __str__(self):
		return 'TODO'

bunky/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse

from .models import User, Bunk

# Views

# Main view
class MainView(generic.ListView):
	context_object_name = 'latest_bunks_list'
	template_name = 'bunky/main.html'

	def get_queryset(self):
		"""Returns the latest 100 Bunks!"""
		return Bunk.objects.filter(time__lte=timezone.now()).order_by('-time')[:100]

# Find view
def find(request):
	# If the request is a post request:
	if request.POST:

		#Extracts the response
		response = request.POST['username']

		# Handles if there is no response
		if not response:
			return render(request, 'bunky/find.html', {
				'error_message': 'Haha, very funny. You need to actually enter a username, doofus.'})

		# Extracts users with the given username and takes the length of that set
		users = User.objects.filter(username=response)
		length = len(users)

		# Handles if there are multiple users of the same username (BUG)
		if length > 1:
			return render(request, 'bunky/find.html', {
				'error_message': 'So uh... this is awkward... There are kinda sorta... multiple users with that username...'})
		# Handles if there is no user with given username
		elif length < 1:
			return render(request, 'bunky/find.html', {
				'error_message': 'Did you even know if there was someone with that username? Because there definitely is not...'})

		# Returns the homepage of the extracted user
		return HttpResponseRedirect(reverse('bunky:home', args=(users[0].id,)))

	# If the request is not a post request (Visiting from MAIN view)
	else:

		return render(request, 'bunky/find.html')

# Home view
def home(request, user_id):
	# Extracts the user object
	user = get_object_or_404(User, pk=user_id)
	# Combines sets of the bunks that contain user as the bunker or bunkee, sorts the set, and takes the first 100
	bunks = (Bunk.objects.filter(to_user=user).union(Bunk.objects.filter(from_user=user))).order_by('-time')[:100]

	return render(request, 'bunky/home.html', {
		'bunks': bunks,
		'user': user})

# Bunk view
def bunk(request, user_id):
	# First confirms that the user exists
	user = get_object_or_404(User, pk=user_id)
	# If the request is a post request:
	if request.POST:

		#Extracts the response
		response = request.POST['username']

		# Handles if there is no response
		if not response:
			return render(request, 'bunky/bunk.html', {
				'error_message': 'Haha, very funny. You need to actually enter a username, doofus.',
				'user' :user})

		# Handles if there are multiple users of the same username (BUG)
		users = User.objects.filter(username=response)
		length = len(users)

		# Handles if there are multiple users of the same username (BUG)
		if length > 1:
			return render(request, 'bunky/bunk.html', {
				'error_message': 'So uh... this is awkward... There are kinda sorta... multiple users with that username...',
				'user': user})
		# Handles if there is no user with given username
		elif length < 1:
			return render(request, 'bunky/bunk.html', {
				'error_message': 'Did you even know if there was someone with that username? Because there definitely is not...',
				'user': user})

		# Creates a new bunk from the extracted information and saves it
		bunk = Bunk(from_user=user, to_user=users[0], time=timezone.now())
		bunk.save()
		return HttpResponseRedirect(reverse('bunky:bunked', args=(bunk.id,)))

	# If the request is not a post request (Visiting from HOME view)
	else:

		return render(request, 'bunky/bunk.html', {
			'user': user})

# Bunk confirmation view
class BunkedView(generic.DetailView):
	model = Bunk
	template_name = 'bunky/bunked.html'

bunky/templates/bunky/bunk.html
<h1>Bunk a User!</h1>

{% if error_message %}
<script>
	alert('{{ error_message }}')
</script>
{% endif %}

<a href="{% url 'bunky:home' user.id %}">Home</a><br><br>

<form action="{% url 'bunky:bunk' user.id %}" method="post">
	{% csrf_token %}
	<input type="text" name="username" id="username"><br><br>
	<input type="submit" value="Bunk!">
</form>

bunky/templates/bunky/bunked.html
<h1>You have successfully bunked {{ bunk.to_user.username }}!</h1>

<a>{{ bunk.to_user.username }}'s profile:</a><br>
<img src="{{ bunk.to_user.photo }}" height = 150><br><br>

<a href="{% url 'bunky:bunk' bunk.from_user.id %}">Bunk again</a><br>
<a href="{% url 'bunky:home' bunk.from_user.id %}">Home</a>

bunky/templates/bunky/find.html
<h1>Enter your username</h1>

{% if error_message %}
<script>
	alert('{{ error_message }}')
</script>
{% endif %}

<form action="{% url 'bunky:find' %}" method="post">
	{% csrf_token %}
	<input type="text" name="username" id="username"><br><br>
	<input type="submit" value="Find">
</form>

bunky/templates/bunky/home.html
<h1>{{ user.username }}'s Homepage</h1>

<img src="{{ user.photo }}" height=200><br><br>

<a href="{% url 'bunky:main' %}">Back</a><br>
<a href="{% url 'bunky:bunk' user.id %}">Bunk Someone?</a><br>
<ul>
	{% for bunk in bunks %}
	<li>
		{{ bunk.from_user.username }} bunk'd {{ bunk.to_user.username }} on {{ bunk.time }}!
	</li>
	{% endfor %}
</ul>

bunky/templates/bunky/main.html
<h1>Welcome to Jitterbunk!</h1>
<a href="{% url 'bunky:find' %}">Log in</a><br>
{% if latest_bunks_list %}
<ul>
	{% for bunk in latest_bunks_list %}
	<li>{{ bunk.from_user.username }} bunk'd {{ bunk.to_user.username }} on {{ bunk.time }}!</li>
	{% endfor %}
</ul>
{% else %}
<p>There hasn't been a SINGLE bunk EVER!</p>
{% endif %}